First draft pipeline with all steps
nf-core/rnavar pull request #3
Opened 2021-06-29 08:51 UTC by praveenraj2018

This is a draft pipeline with all steps implemented

2021-07-02 07:54 UTC, maxulysse commented
Why is there one `rnavar.nf` script and one `rnavar_bk.nf` script?

2021-07-02 09:48 UTC, praveenraj2018 commented
> Why is there one `rnavar.nf` script and one `rnavar_bk.nf` script?

I will have to remove the *bk.nf. Taken as a backup.

2021-07-05 09:26 UTC, maxulysse commented
OK, I think the last thing that we now need would be to fix the nf-core lint.

2021-07-05 09:48 UTC, praveenraj2018 commented
> OK, I think the last thing that we now need would be to fix the nf-core lint.

Yes, That's what I am doing now...

2021-07-05 09:49 UTC, maxulysse commented
Don't hesitate to message me on Slack if you need help with that

2021-07-06 07:54 UTC, maxulysse commented on .nf-core-lint.yml
> +  - docs/images/nf-core-rnavar_logo.png
```suggestion
```
I don't think you need these files to be out of the nf-core linting

2021-07-06 07:56 UTC, maxulysse requested changes
Looking very good.
Just need to remove the dockerfile and environment.yml file and I think we're good with this PR

2021-07-06 07:56 UTC, maxulysse commented on Dockerfile
> +RUN conda env export --name nf-core-rnavar-3.1 > nf-core-rnavar-3.1.yml
This file can be deleted

2021-07-06 07:56 UTC, maxulysse commented on environment.yml
> +  - bioconda::multiqc=1.11
This file can be deleted too

2021-07-13 08:09 UTC, merged